openai_api_key = "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"
openai_project = "proj_oCt5LGaVEjXWxPyLLmUDL8yS"
openai_organization = "org-5S9TCJj9up0nlCFz3G8ZlCP2"
