openai_api_key = "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"
openai_project = "proj_oCt5LGaVEjXWxPyLLmUDL8yS"
openai_organization = "org-5S9TCJj9up0nlCFz3G8ZlCP2"
